#!/usr/bin/env node
// tslint:disable
const path = require('path')
const CopyWebpackPlugin = require('copy-webpack-plugin')

module.exports = {
  mode: 'production',
  target: 'node',
  entry: './src/index.ts',
  module: {
    rules: [
      {
        test: /\.(ts|js)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/env', '@babel/typescript'],
            plugins: ['transform-async-to-promises']
          }
        }
      }
    ]
  },
  // devtool: 'source-map',
  resolve: {
    extensions: ['.ts', '.js']
  },
  output: {
    filename: 'index.js',
    libraryTarget: 'commonjs',
    path: path.resolve(__dirname, 'lib')
  },
  plugins: [new CopyWebpackPlugin(['LICENSE', '*.md', 'package*.json'])]
}
